In [87]:
# Linear Regression

In [88]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [89]:
dataset = pd.read_csv("Salary_Data.csv")

In [90]:
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [91]:
x = dataset.iloc[:,0:1].values

In [92]:
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [93]:
y = dataset.iloc[:,-1].values

In [94]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [95]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2,random_state=10)

In [96]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [97]:
regressor.coef_

array([9356.86299354])

In [98]:
regressor.intercept_

26089.09663241673

In [99]:
#salary = 9356*Exp + 26089

In [100]:
x_new = pd.read_csv('Salary_New.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Desktop/DWM/DWM_ Prac_12/Salary_New.csv'

In [ ]:
x_new

In [ ]:
x_new = x_new.iloc[:,:].values

In [ ]:
x_new

In [ ]:
y_pred_test=regressor.predict(x_test)

In [ ]:
y_pred_new=regressor.predict(x_new)

In [ ]:
y_pred_test

In [ ]:
y_pred_new

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred_test)

In [ ]:
y_test

In [ ]:
y_pred_new

In [ ]:
plt.scatter(x_train,y_train, color = 'red')
plt.plot(x_train, regressor.predict(x_train), color='blue')

In [ ]:
plt.scatter(x_test,y_test, color = 'red')
plt.plot(x_test, regressor.predict(x_test), color='blue')

In [ ]:
dataset = pd.read_csv('50_Startups.csv')

In [ ]:
dataset

In [ ]:
x = dataset.iloc[:,0:4].values

In [ ]:
x

In [ ]:
y = dataset.iloc[:,-1].values

In [ ]:
y

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,3] = labelencoder_x.fit_transform(x[:,3])

In [ ]:
x

In [ ]:
pd.DataFrame(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

In [ ]:
y_pred = regressor.predict(x_test)

In [ ]:
y_pred

In [ ]:
y_test

In [ ]:
regressor.coef_

In [ ]:
regressor.intercept_